#! /bin/bash

mdfiles=$(find -name "*.md" -not -path "./node_modules/*")

for file in $mdfiles; do
    marp --html $file
done

if [ -d "dist" ]; then
    rm -rf dist
fi

mkdir dist

htmlfiles=$(find -name "*.html" -not -path "./node_modules/*")

for file in $htmlfiles; do
    mkdir -p "dist/${file%/*}"
    cp $file "dist/$file"
done

assetfolders=$(find -name "assets" -not -path "./node_modules/*")

for folder in $assetfolders; do
    mkdir -p "dist/$folder"
    cp -R "$folder/"* "dist/$folder"
done
