#! /bin/bash

npx sass src/styles/theme.scss src/styles/theme.css

echo "[ INFO ] Find all files with name match *.md"
mdfiles=$(find -name "*.md" -not -path "./node_modules/*")

echo "[ INFO ] Convert markdown files to html files"
for file in $mdfiles; do
    marp --html $file --title "Phân tích thiết kế hệ thống thông tin" --theme src/styles/theme.css
done

echo "[ INFO ] Create dist directory"
if [ -d "dist" ]; then
    echo "[ INFO ] dist directory is existing!"
    echo "[ INFO ] remove dist directory"
    rm -rf dist
fi

mkdir dist

echo "[ INFO ] Find all files with name match *.html"

htmlfiles=$(find -name "*.html" -not -path "./node_modules/*")

echo "[ INFO ] Move html files to dist directory"

for file in $htmlfiles; do
    echo -e "\t[ TASK ] Create directory dist/${file%/*}"
    mkdir -p "dist/${file%/*}"
    echo -e "\t[ TASK ] Move $file to dist/$file"
    mv $file "dist/$file"
done

echo "[ INFO ] Find all directories with name match assets"

assetfolders=$(find -name "assets" -not -path "./node_modules/*")

for folder in $assetfolders; do
    echo -e "\t[ TASK ] Make directory dist/$folder"
    mkdir -p "dist/$folder"
    echo -e "\t[ TASK ] Copy $folder/ to dist/$folder"
    cp -R "$folder/"* "dist/$folder"
done

mv dist/src/* dist
rm -rf dist/src

echo "Move dist/src/* to dist"
echo "Remove dist/src"

echo "Build success!"
